# Домашнє завдання № 1

In [2]:
import numpy as np

#### 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [45]:
a = np.arange(1, 11)
print(f'a = {a}')

a = [ 1  2  3  4  5  6  7  8  9 10]


#### 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [93]:
m = np.zeros((3, 3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [94]:
m = np.random.randint(1, 11, (5, 5))
print(m)

[[ 9  6  3  2 10]
 [ 3  7 10  7  5]
 [ 2  5  5  1  7]
 [10  9  4  5  2]
 [ 4  6  7  8  8]]


#### 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [32]:
m = np.random.randint(0, 2, (4, 4))
print(m)

[[0 1 0 1]
 [1 1 0 0]
 [1 1 1 0]
 [1 1 1 1]]


#### 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [44]:
a = np.random.randint(1, 11, 5)
b = np.random.randint(1, 11, 5)
print(f'a = {a}')
print(f'b = {b}')
print(f'a + b = {a+b}')
print(f'a - b = {a-b}')
print(f'a * b = {a*b}')

a = [9 5 2 7 2]
b = [ 3  3 10  6  2]
a + b = [12  8 12 13  4]
a - b = [ 6  2 -8  1  0]
a * b = [27 15 20 42  4]


#### 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [53]:
a = np.random.rand(7)
b = np.random.rand(7)
print(f'a = {a}')
print(f'b = {b}')
print(f'scalar product = {np.dot(a, b)}')

a = [0.4172126  0.81834357 0.81218567 0.48601078 0.5046514  0.88676141
 0.78902515]
b = [0.92717288 0.05979733 0.41884059 0.03689777 0.15838809 0.88636148
 0.92292973]
scalar product = 2.38800869525521


#### 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [59]:
a = np.random.randint(1, 11, (2, 2))
b = np.random.randint(1, 11, (2, 3))
c = np.dot(a, b)
print(a)
print(b)
print(c)

[[6 9]
 [2 1]]
[[6 4 1]
 [5 4 2]]
[[81 60 24]
 [17 12  4]]


#### 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [60]:
a = np.random.randint(1, 11, (3, 3))
a_inv = np.linalg.inv(a)
print(a)
print(a_inv)

[[ 7  4 10]
 [10  3  5]
 [ 6  1  2]]
[[-0.03030303 -0.06060606  0.3030303 ]
 [-0.3030303   1.39393939 -1.96969697]
 [ 0.24242424 -0.51515152  0.57575758]]


#### 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [71]:
a = np.random.randint(0, 2, (4, 4))
b = a.T
print(a)
print(b)

[[1 1 1 1]
 [1 0 1 0]
 [0 1 0 1]
 [0 0 0 0]]
[[1 1 0 0]
 [1 0 1 0]
 [1 1 0 0]
 [1 0 1 0]]


#### 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [91]:
a = np.random.randint(1, 11, (3, 4))
b = np.linspace(1, 10, 4)
c = np.dot(a, b)
print(a)
print(b)
print(c)

[[ 3 10  3 10]
 [10  4 10  1]
 [ 2 10  1  7]]
[ 1.  4.  7. 10.]
[164. 106. 119.]


#### 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [109]:
a = np.random.rand(2, 3)
b = np.linspace(0, 2, 3)
c = np.dot(a, b)
print(a)
print(b)
print(c)

[[0.58150269 0.10927908 0.55191026]
 [0.33826145 0.91135577 0.60730221]]
[0. 1. 2.]
[1.2130996  2.12596019]


#### 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [110]:
a = np.random.randint(1, 11, (2, 2))
b = np.random.randint(1, 11, (2, 2))
c = a * b
print(a)
print(b)
print(c)

[[6 1]
 [4 9]]
[[ 3  6]
 [ 4 10]]
[[18  6]
 [16 90]]


#### 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток

In [112]:
a = np.random.randint(1, 11, (2, 2))
b = np.random.randint(1, 11, (2, 2))
c = np.dot(a, b)
print(a)
print(b)
print(c)

[[4 6]
 [5 4]]
[[3 9]
 [5 5]]
[[42 66]
 [35 65]]


#### 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [114]:
a = np.random.randint(1, 101, (5, 5))
print(a)
print(a.sum())

[[24 55 79 49 20]
 [31 29 41 89 51]
 [52 98 54 58 29]
 [48  5 64 17 34]
 [33 67 56 91 59]]
1233


#### 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [115]:
a = np.random.randint(1, 11, (4, 4))
b = np.random.randint(1, 11, (4, 4))
c = a - b
print(a)
print(b)
print(c)

[[8 1 2 1]
 [3 3 4 2]
 [4 1 8 7]
 [3 8 8 3]]
[[ 9  7 10  7]
 [10  7  5  6]
 [ 3  9 10  7]
 [ 7  3  2  7]]
[[-1 -6 -8 -6]
 [-7 -4 -1 -4]
 [ 1 -8 -2  0]
 [-4  5  6 -4]]


#### 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [122]:
a = np.random.rand(3, 3)
b = a.sum(axis=1)
print(a)
print(b)

[[0.56486379 0.86366527 0.71217578]
 [0.48026562 0.97053184 0.58014695]
 [0.46911358 0.53779276 0.44160325]]
[2.14070484 2.03094442 1.44850959]


#### 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створіть матрицю з квадратами цих чисел.

In [125]:
a = np.random.randint(1, 11, (3, 4))
b = a ** 2
print(a)
print(b)

[[ 5  8  6  7]
 [ 4  1  9  3]
 [ 4 10  2  5]]
[[ 25  64  36  49]
 [ 16   1  81   9]
 [ 16 100   4  25]]


#### 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел

In [131]:
a = np.linspace(1, 50, 4, dtype=int)
b = a ** 0.5
print(a)
print(b)

[ 1 17 33 50]
[1.         4.12310563 5.74456265 7.07106781]
